name: SpigotBlankPlugin
main: com.meeku.tutorialplugin.SpigotBlankPlugin
version: 1.0
commands:
    addbcticket:
        description: Adds a ticket to the current pot.
        usage: /addbcticket <uuid>
    buycraftlottocheck:
        description: Checks the current statistics of the Buycraft lottery.
        usage: /buycraftlottocheck
